#cloud-config
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
	disable_components: []
	fallback: offline-install
	geoip: true
	mirror-selection:
  	primary:
  	- country-mirror
  	- arches: &id001
    	- amd64
    	- i386
    	uri: http://archive.ubuntu.com/ubuntu/
  	- arches: &id002
    	- s390x
    	- arm64
    	- armhf
    	- powerpc
    	- ppc64el
    	- riscv64
    	uri: http://ports.ubuntu.com/ubuntu-ports
	preserve_sources_list: false
	security:
	- arches: *id001
  	uri: http://security.ubuntu.com/ubuntu/
	- arches: *id002
  	uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
	install: false
  drivers:
	install: false
  identity:
	hostname: gf-Standard-PC-Q35-ICH9-2009
	password: $6$D2QXKdlwpULi16Vg$sMdG.j6b9r2UvZSoeCiO7R/Elv/3YNrGOkwkl7K3Z1F5w57lK9Vr749wyLo4fzhAfPB6BObrRRHXmLUdm5WSu.
	realname: gf
	username: gf
  kernel:
	package: linux-generic-hwe-24.04
  keyboard:
	layout: fr
	toggle: null
	variant: latin9
  locale: fr_FR.UTF-8
  network:
	ethernets:
  	enp1s0:
    	dhcp4: true
	version: 2
  oem:
	install: auto
  source:
	id: ubuntu-desktop-minimal
	search_drivers: false
  ssh:
	allow-pw: true
	authorized-keys: []
	install-server: false
  storage:
	config:
	- ptable: gpt
  	path: /dev/vda
  	wipe: superblock-recursive
  	preserve: false
  	name: ''
  	grub_device: true
  	id: disk-vda
  	type: disk
	- device: disk-vda
  	size: 1048576
  	flag: bios_grub
  	number: 1
  	preserve: false
  	offset: 1048576
  	path: /dev/vda1
  	id: partition-0
  	type: partition
	- device: disk-vda
  	size: 2147483648
  	wipe: superblock
  	number: 2
  	preserve: false
  	offset: 2097152
  	path: /dev/vda2
  	id: partition-1
  	type: partition
	- fstype: ext4
  	volume: partition-1
  	preserve: false
  	id: format-0
  	type: format
	- device: disk-vda
  	size: 24692916224
  	wipe: superblock
  	number: 3
  	preserve: false
  	offset: 2149580800
  	path: /dev/vda3
  	id: partition-2
  	type: partition
	- volume: partition-2
  	keyfile: /tmp/luks-key-pl8_z_k0
  	recovery_keyfile: null
  	path: /dev/mapper/dm_crypt-0
  	preserve: false
  	id: dm_crypt-0
  	type: dm_crypt
	- name: ubuntu-vg
  	devices:
  	- dm_crypt-0
  	preserve: false
  	id: lvm_volgroup-0
  	type: lvm_volgroup
	- name: ubuntu-lv
  	volgroup: lvm_volgroup-0
  	size: 24675090432B
  	wipe: superblock
  	preserve: false
  	path: /dev/ubuntu-vg/ubuntu-lv
  	id: lvm_partition-0
  	type: lvm_partition
	- fstype: ext4
  	volume: lvm_partition-0
  	preserve: false
  	id: format-1
  	type: format
	- path: /
  	device: format-1
  	id: mount-1
  	type: mount
	- path: /boot
  	device: format-0
  	id: mount-0
  	type: mount
  timezone: Europe/Paris
  updates: security
  version: 1


